<?php

$aConfig[$sAppName]['dev'] = array(
                                    'siteUrl' => 'http://'.$_SERVER["HTTP_HOST"],
                                    'rootDir' => 'D:/personal/admin',
                                    'language'=>'en',
                                    'homeModule'=>'dashboard',
                                    'homeAction'=>'home',
                                    'loginModule'=>'dashboard',
                                    'loginAction'=>'home',
                                    'dbHost'=>'localhost',
                                    'dbUser'=>'root',
                                    'dbPassword'=>'',
                                    'dbName'=>'primary_school',
                                    'sSessionName'=>'userSession',
                                    'routerClassName' => 'routers',
                                    'dtDateTime' => "Y-m-d H:i:s",
                                    'checkSlug'=>false,
                                    'siteTitle'=>"hello's",
                                );
// $aConfig[$sAppName]['prod'] = array(
//                                     'siteUrl' => 'http://'.$_SERVER["HTTP_HOST"],
//                                     'rootDir' => '/home2/righters/public_html/righters_staging/rightersgroup-maildb',
//                                     'ongageApi'=> 'https://api.ongage.net/',
//                                     'username' => 'jaldip@stepinsolutions.in',
//                                     'password' => 'UdM@t3^$z5NTrnlz',
//                                     'account_code' => 'righters_group',
//                                     'language'=>'en',
//                                     'homeModule'=>'dashboard',
//                                     'homeAction'=>'data',
//                                     'loginModule'=>'users',
//                                     'loginAction'=>'login',
//                                     'dbHost'=>'localhost',
//                                     'dbUser'=>'righters_staging',
//                                     'dbPassword'=>'[^DHI2lG7=~!',
//                                     'dbName'=>'righters_staging',
//                                     'nPagerLength'=>'',
//                                     'nPerPageRecords'=>'',
//                                     'sSessionName'=>'userSession',
//                                     'routerClassName' => 'routers',
//                                     'dtDateTime' => "Y-m-d H:i:s",
//                                     'checkSlug'=>false,
//                                     'siteTitle'=>"Righter's",
//                                     'concurrencyForOngage'=>10,
//                                     'doNotSendOngageRequestFor'=>1200,
//                                     'maxRecordsToBeProcessed'=>300000,
//                                     'inboxGenieApi'=>"https://api.inboxgenie.com/",
//                                     'inboxGenieContext'=>3084,
//                                     'plateformIdForInboxGenie' =>2,
//                                     'inboxGenieAuthorization'=>"Basic UmlnaHRlcnNHcm91cFVzZXI6U2t4ZzNGOHlCTnJHdFJ2RnhtOUg3Zm5mUw==",
//                                     'inboxGeniePageSize'=>10000,
//                                     'maxRetry'=>3,
//                                     'inboxGenieEvent'=>array(
//                                         'click'=>1,
//                                         'send'=>6,
//                                         'open'=>14,
//                                         'optout'=>17,
//                                         'complaint'=>23,
//                                         'hardbounce'=>29,
//                                         'softbounce'=>30,
//                                         'mailblock'=>31,
//                                     ),
//                                 );