<?php

$aConfig[$sAppName]['dev'] = array(
    'siteUrl' => 'http://' . $_SERVER["HTTP_HOST"],
    'rootDir' => 'D:/personal/pree/rmcadmin16',
    'language' => 'en',
    'homeModule' => 'dashboard',
    'homeAction' => 'home',
    'loginModule' => 'users',
    'loginAction' => 'login',
    'dbHost' => 'localhost',
    'dbUser' => 'root',
    'dbPassword' => '',
    'dbName' => 'primary_school',
    'sSessionName' => 'userSession',
    'routerClassName' => 'routers',
    'dtDateTime' => "Y-m-d H:i:s",
    'checkSlug' => false,
    'siteTitle' => "Admin Panel",
);
$aConfig[$sAppName]['prod'] = array(
    'siteUrl' => 'http://' . $_SERVER["HTTP_HOST"],
    'rootDir' => '/home/u657523813/domains/rmcschoolno16.com/public_html/adminRmcSchoolNo16',
    'language' => 'en',
    'homeModule' => 'dashboard',
    'homeAction' => 'home',
    'loginModule' => 'users',
    'loginAction' => 'login',
    'dbHost' => 'localhost',
    'dbUser' => 'u657523813_rmcschoolno16',
    'dbPassword' => 'd:9GQYQVZ>a5',
    'dbName' => 'u657523813_rmcschoolno16',
    'sSessionName' => 'userSession',
    'routerClassName' => 'routers',
    'dtDateTime' => "Y-m-d H:i:s",
    'checkSlug' => false,
    'siteTitle' => "Admin Panel",
);
